// Common lodge/hotel room amenities offered as quick-pick options on the
// Add/Edit Room form. Not exhaustive by design — "Other" lets staff type
// anything not on this list.
export const ROOM_AMENITIES: string[] = [
  'Wi-Fi',
  'Air Conditioning',
  'Fan',
  'Television',
  'Mini Bar',
  'Room Service',
  'Private Balcony',
  'Private Bathroom',
  'Hot Water',
  'Heating',
  'Fireplace',
  'Mosquito Net',
  'In-Room Safe',
  'Hairdryer',
  'Iron & Ironing Board',
  'Tea/Coffee Maker',
  'Breakfast Included',
  'Free Parking',
  'Swimming Pool Access',
  'Gym Access',
  'Pet Friendly',
  'Non-Smoking',
  'Wheelchair Accessible',
  'Kitchenette',
  'Laundry Service',
  'Garden View',
  'Mountain View',
  'Lake/River View',
  'Work Desk',
  'Bathtub',
]
